.PHONY: build bootstrap test clean help

help:
	@echo "Flower Compiler\t\t:   Build Commands"
	@echo "\tmake build\t:   Build compiler from source"
	@echo "\tmake bootstrap\t:   Build compiler with verification"
	@echo "\tmake test\t:   Run test suite"
	@echo "\tmake clean\t:   Remove build artifacts"

# build: 
# 	./bin/Flower ./src/main.flo ./bin/Flower.c
# 	gcc ./bin/Flower.c -o bin/Flower.new
# 	mv bin/Flower.new bin/Flower

bootstrap:
	./scripts/build.sh
	@echo "Verified bootstrap build complete"

rebuild: 
	clean build
	@echo "Clean rebuild complete"

test:
	mkdir -p output
	./bin/Flower ./examples/test.flo ./output/out

clean:
	rm -rf build/ output/
	rm -f bin/Flower_* bin/Flower.c
	@echo "Removed artifacts"

all: build test